---

- name: set fact mongod_auth=true
  set_fact: mongod_auth=true

- name: set fact mongo_type=mongos
  set_fact: mongo_type=mongos

- name: Create config server data directory
  file: path="{{ mongod_datadir_prefix }}/{{ mongo_type }}" owner=mongodb group=mongodb state=directory

- name: set fact mongod_port="{{ mongos_port }}"
  set_fact: mongod_port="{{ mongos_port }}"

- name: Create the mongos init file for Debian
  template: src=mongod_debian_init.j2 dest=/etc/init.d/mongos mode=755
  when: ansible_os_family == "Debian"

- name: Enable mongos service  
  command: "{{ item }}"
  with_items:
    - update-rc.d mongos defaults
    - update-rc.d mongos enable 
  when: ansible_os_family == "Debian"

- name: generate the mongos configuration file
  template: src=mongod.conf.j2 dest=/etc/mongos.conf

- name: Start the mongos service for redhat variants
  command: creates=/var/lock/subsys/mongos /etc/init.d/mongos start
  when: ansible_os_family == "RedHat"

- name: Start the mongos service for Ubuntu variants 
  service: name=mongos state=started
  when: ansible_os_family == "Debian"
