---

# installs mongo server 

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the mongodb server RPM package
  yum: name="{{ item }}" state=installed
  with_items: "{{ mongo_server_pkgs }}"
  when: ansible_os_family == "RedHat"

- name: Install the mongodb server APT package
  apt: name="{{ item }}" state=installed update_cache=yes
  with_items: "{{ mongo_server_pkgs }}"
  when: ansible_os_family == "Debian"
