- name: Generate the keyfile for authentication
  set_fact: mongod_secret_key="{{ lookup('password', 'secret length=256 chars=ascii_letters,digits') }}"

- name: Copy the keyfile for authentication
  copy: src=secret dest={{ mongod_datadir_prefix }}/secret owner=mongodb group=mongodb mode=0400

