---

# top-level

- name: install mongo base packages
  include: mongod.yml 

- name: configure config server 
  include: configure_cs.yml

- name: configure mongos server
  include: configure_mongos.yml

- name: add shards
  include: shards.yml

#- name: uninstall mongo 
#  include: uninstall.yml
